---

- name: Configuring EC2 Instace
  hosts: nodes
  user: ubuntu
  become: True
  vars_files:
    - variables/ec2_configs.yml

  roles:
#    - common-host
#    - php5
#    - percona
#    - nginx
#    - drupal
    - civicrm
#    - { role: certbot, when: site.ssl }
